### ISSUE TITLE
Fix for M4 PKGBUILD install location

### ISSUE THREAD

**Issue by tarmiste** [benvd/lfs-pacman#1]
The m4 PKGBUILD install function puts the m4 files in a different place than where the LFS build 
puts them.

Making the following change makes the m4 files install to the same place as in a normal LFS build.

diff -r /home/koo/lfs-pacman/packages/m4/PKGBUILD ./packages/m4/PKGBUILD
23c23
<     make prefix=${pkgdir} install
---
>     make prefix=${pkgdir}/usr install

**Comment by benvd** [comment]
You're right, thanks. Fixed in 81f7383.
