### ISSUE TITLE
Problems with fakeroot (util-linux,getopt)

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [benvd/lfs-pacman#3]
Libarchive did not compile, kept giving messages like:
`undefined reference to `lzma_end'`

I was able to compile it using the `--without-lzma` flag.

When creating the pacman package for pacman using makepkg I got:
`/tools/bin/fakeroot: line 46: getopt: command not found
/tools/bin/fakeroot: line 50: getopt: command not found`

This is because util-linux and fakeroot depends on it isn't in the toolchain. This is has to be installed to the toolchain first. But I've been unable to do so. I am guessing it depends on quite some chapter 6 packages that have to be installed first.

**Comment by LevitatingBusinessMan** [comment]
I made a patch which just comments out all the lines testing with getopt.
https://gist.github.com/LevitatingBusinessMan/e3eef57edfcbf6e65045494be4c67c85

**Comment by benvd** [comment]
Not sure why it worked for me without getopt... However, I'm in the process of updating this guide for LFS 9.1, and indeed, I now encounter the getopt errors as well.

And actually, building util-linux at this stage is fairly simple, as it turns out.
